spring:
  application:
    name: NotificationService
  mail:
    host: smtp.gmail.com
    port: 587
    username: vut70141@gmail.com
    password: fsuwhqanuedaxupu
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    function:
      definition: transactionConsumer;consumeAndReport
    stream:
      bindings:
        transactionConsumer-out-0:
          destination: financial-transactions
        consumeAndReport-out-0:
          destination: financial-transactions
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            auto.create.topics.enable: "true"
  integration:
    poller:
      fixed-delay: 5000
server:
  port: 8085
