server:
  port: 8084
spring:
  application:
    name: LoanService
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/LoanService
    password: vdt1410
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        envers.audit_table_suffix: _AUD
        envers.revision_field_name: REV
        envers.revision_type_field_name: REV_TYPE
        envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
    show-sql: true
  cloud:
    function:
      definition: cbv
    stream:
        bindings:
          transactionConsumer-out-0:
            destination: financial-transactions
          consumeAndReport-out-0:
            destination: financial-transactions
        kafka:
          binder:
            brokers: localhost:9092
            consumer-properties:
              auto.create.topics.enable: "true"
logging:
  file:
    path: logs/loan_service
  level:
    org.demo.loanservice.config.CustomRequestLoggingFilter: DEBUG
